# Generated by Django 2.2.6 on 2019-10-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='disability',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='other_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
