# Generated by Django 2.2.6 on 2019-10-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisapp', '0003_auto_20191014_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='fingerprint',
            field=models.CharField(default='atitude-E7240 ~/Desktop/milestone/wis ', max_length=48),
            preserve_default=False,
        ),
    ]
