# Generated by Django 2.2.6 on 2019-10-14 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wisapp', '0004_staff_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='date_of_employment',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='date_of_retirement',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
