# Generated by Django 2.2.6 on 2019-10-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisapp', '0005_auto_20191014_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='date_of_employment',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date_of_retirement',
            field=models.DateTimeField(),
        ),
    ]
