# Generated by Django 2.2.7 on 2019-11-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisapp', '0007_staff_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='nimc',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
