# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-14 13:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('bn_rc', models.CharField(max_length=150)),
                ('tin', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('email', models.CharField(blank=True, max_length=150)),
                ('contact_num', models.CharField(blank=True, max_length=150)),
                ('owner_name', models.CharField(max_length=150)),
                ('location_lga', models.CharField(blank=True, max_length=150)),
                ('tax_collector', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_no', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('supervisor', models.CharField(max_length=150)),
                ('is_supervisor', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
