# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-22 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tax_app', '0006_auto_20191022_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tax_app.Business_Category'),
            preserve_default=False,
        ),
    ]
